# Generated by Django 5.2.4 on 2026-04-13 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usergoal",
            name="target_hours",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
