# Generated by Django 5.2.4 on 2026-05-26 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_usergoal_target_hours"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletedAccountRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_user_id", models.PositiveIntegerField()),
                ("username", models.CharField(max_length=150)),
                ("masked_email", models.CharField(blank=True, max_length=254)),
                ("date_joined", models.DateTimeField()),
                ("deletion_requested_at", models.DateTimeField()),
                ("purged_at", models.DateTimeField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["original_user_id"], name="deleted_acct_user_idx"
                    ),
                    models.Index(fields=["purged_at"], name="deleted_acct_purged_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AccountDeletionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_at", models.DateTimeField()),
                ("scheduled_delete_at", models.DateTimeField()),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("purged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deletion_request",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["scheduled_delete_at"], name="acct_del_scheduled_idx"
                    ),
                    models.Index(
                        fields=["cancelled_at"], name="acct_del_cancelled_idx"
                    ),
                    models.Index(fields=["purged_at"], name="acct_del_purged_idx"),
                ],
            },
        ),
    ]
