# Generated by Django 5.2.4 on 2026-08-25 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def mark_existing_accounts_verified(apps, schema_editor):
    """이미 쓰고 있던 계정은 코드 인증 도입으로 로그인이 막히면 안 된다."""
    User = apps.get_model("auth", "User")
    EmailVerification = apps.get_model("users", "EmailVerification")
    now = timezone.now()
    EmailVerification.objects.bulk_create(
        [
            EmailVerification(user_id=user_id, verified_at=now)
            for user_id in User.objects.values_list("id", flat=True)
        ],
        ignore_conflicts=True,
    )


def drop_verification_rows(apps, schema_editor):
    apps.get_model("users", "EmailVerification").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_account_deletion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verification",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailVerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("signup", "가입 인증"),
                            ("password_reset", "비밀번호 재설정"),
                        ],
                        max_length=20,
                    ),
                ),
                ("code_hash", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "purpose", "consumed_at"],
                        name="verif_code_lookup_idx",
                    ),
                    models.Index(fields=["created_at"], name="verif_code_created_idx"),
                ],
            },
        ),
        migrations.RunPython(
            mark_existing_accounts_verified,
            drop_verification_rows,
        ),
    ]
