# Generated by Django 5.2.4 on 2026-10-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_emailverification_emailverificationcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergoal",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
