# Generated by Django 5.2.4 on 2026-04-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_remove_timeblock_deleted_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeblock",
            name="memo",
            field=models.CharField(
                blank=True,
                help_text="최대 500자까지 입력 가능",
                max_length=500,
                verbose_name="메모",
            ),
        ),
    ]
