# Generated by Django 5.2.4 on 2026-04-13 10:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0003_remove_tag_unique_user_tag_name_tag_is_default_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="카테고리명"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="슬러그")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "color",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="올바른 HEX 색상 코드를 입력하세요 (예: #FF5733)",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                        verbose_name="색상",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="표시 순서"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
            ],
            options={
                "verbose_name": "카테고리",
                "verbose_name_plural": "카테고리들",
                "ordering": ["display_order"],
            },
        ),
        migrations.AddField(
            model_name="tag",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tags",
                to="tags.category",
                verbose_name="카테고리",
            ),
        ),
    ]
