# Generated by Django 5.2.4 on 2026-08-01 03:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0008_sian_category_palette"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(
                blank=True,
                help_text="카테고리에서 자동으로 정해집니다.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="올바른 HEX 색상 코드를 입력하세요 (예: #FF5733)",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
                verbose_name="색상",
            ),
        ),
    ]
